### ISSUE TITLE
https://lang-jvm.s3.amazonaws.com is down - is there a backup?

### ISSUE THREAD

**Issue by danielalexiuc** [heroku/heroku-buildpack-jvm-common#106]
https://lang-jvm.s3.amazonaws.com is currently not resolving... is there a fallback in case it goes down?

**Comment by jkutner** [comment]
@danielalexiuc sorry for the trouble. There is no backup for `https://lang-jvm.s3.amazonaws.com`, in part because when S3 is down there are usually many other problems to go with something like this. In this case it turned out to be an acute failure for just a few buckets.

It is possible to override `JDK_BASE_URL` and `JDK_URL_1_8` (or similar per version) however. You could then reference your own binaries.
